<?php

/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2025-06-16 11:38:40
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2025-07-15 18:38:04
 */

return [
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/app/app'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET nav' => 'nav',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/member'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET store'                   => 'store',
            'GET cloud'                   => 'cloud',
            'POST create'                 => 'create',
            'POST,GET change-field'       => 'change-field',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/wechat/member'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET list'               => 'list',
            'GET role'               => 'role',
            'POST role-money'        => 'role-money',
            'POST,GET change-status' => 'change-status',
            'POST permission'        => 'permission',
            'POST set-role'          => 'set-role',
            'POST set-money'         => 'set-money',
            'POST add'               => 'add',
            'POST bind-openid'       => 'bind-openid',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/memberrole'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET list'                    => 'list',
            'POST create'                 => 'create',
            'POST permission'             => 'permission',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET get_options'             => 'get-options',
            'POST save_permissions'       => 'save-permissions',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/permission'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET list'                    => 'list',
            'GET addons'                  => 'addons',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/role'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/rolepermission'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/money'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET enum'                    => 'enum',
            'GET role'                    => 'role',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/cloud/addons'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET enum'                    => 'enum',
            'GET role'                    => 'role',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/cloud/addons-cate'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET list'                    => 'list',
            'POST addons'                 => 'addons',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET enum'                    => 'enum',
            'GET role'                    => 'role',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/cloud/addons'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET addons-auth'             => 'addons-auth',
            'POST create'                 => 'create',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET enum'                    => 'enum',
            'GET role'                    => 'role',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/departments'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET group'                   => 'group',
            'POST create'                 => 'create',
            'POST auth-data'              => 'auth-data',
            'POST auth-list'              => 'auth-list',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'GET enum'                    => 'enum',
            'GET level'                   => 'level',
            'GET store-level'             => 'store-level',
        ],
    ],
    //业务中心角色
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/auth/group-yw'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET index'                   => 'index',
            'GET rule'                    => 'rule',
            'GET levels'                  => 'levels',
            'GET addons'                  => 'addons',
            'GET init'                    => 'init',
            'POST create'                 => 'create',
            'POST  route'                 => 'route',
            'POST,PUT update/<id>'        => 'update',
            'POST,GET,DELETE delete/<id>' => 'delete',
            'GET view/<id>'               => 'view',
            'POST assign/<id>'            => 'assign',
            'POST remove/<id>'            => 'remove',
            'POST change'                 => 'change',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/auth/assignment-yw'],
        'pluralize'     => false,
        'extraPatterns' => [
            'GET view/<id>'    => 'view',
            'POST assign/<id>' => 'assign',
            'POST revoke/<id>' => 'revoke',
            'POST change'      => 'change',
            'POST create-auth' => 'create-auth',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/auth/admin-user-yw'],
        'pluralize'     => false,
        'extraPatterns' => [
            'POST,GET index'   => 'index',
            'POST create'      => 'create',
            'POST update'      => 'update',
            'POST auth-link'   => 'auth-link',
            'GET link'         => 'link',
            'GET user'         => 'user',
            'GET view/<id>'    => 'view',
            'POST assign/<id>' => 'assign',
            'POST remove/<id>' => 'remove',
            'POST change'      => 'change',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/section'],
        'pluralize'     => false,
        'extraPatterns' => [
            'POST,GET index' => 'index',
            'POST create'    => 'create',
            'POST update'    => 'update',
            'GET view/<id>'  => 'view',
            'GET detail'     => 'detail',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/setting'],
        'pluralize'     => false,
        'extraPatterns' => [
            'POST,GET index'    => 'index',
            'POST create'       => 'create',
            'POST update'       => 'update',
            'GET view/<id>'     => 'view',
            'POST,GET sections' => 'sections',
            'GET info'          => 'info',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/store-setting'],
        'pluralize'     => false,
        'extraPatterns' => [
            'POST,GET index'    => 'index',
            'POST create'       => 'create',
            'POST update'       => 'update',
            'GET view/<id>'     => 'view',
            'POST,GET sections' => 'sections',
        ],
    ],
    [
        'class'         => 'yii\rest\UrlRule',
        'controller'    => ['diandi_auth/app/nav'],
        'pluralize'     => false,
        'extraPatterns' => [
            'POST,GET index'    => 'index',
            'POST create'       => 'create',
            'POST update'       => 'update',
            'GET list'          => 'list',
            'GET view/<id>'     => 'view',
            'POST,GET sections' => 'sections',
        ],
    ],
];
