<?php

namespace common\modules\openWeixin\models\enums;

use common\components\BaseEnum;

class OpenWeixinAuthCode extends BaseEnum
{
    const authcode1 = 1;//	消息管理
    const authcode2 = 2;//	用户管理
    const authcode3 = 3;//	账号服务
    const authcode4 = 4;//	网页服务
    const authcode5 = 5;//	微信小店
    const authcode6 = 6;//	微信多客服
    const authcode7 = 7;//	群发与通知
    const authcode8 = 8;//	微信卡券
    const authcode9 = 9;//	微信扫一扫
    const authcode10 = 10;//	微信连WIFI
    const authcode11 = 11;//	素材管理
    const authcode12 = 12;//	微信摇周边
    const authcode13 = 13;//	微信门店
    const authcode15 = 15;//	菜单管理
    const authcode22 = 22;//	城市服务
    const authcode23 = 23;//	广告管理
    const authcode24 = 24;//	开放平台账号管理
    const authcode26 = 26;//	微信电子发票
    const authcode27 = 27;//	快速注册小程序
    const authcode33 = 33;//	小程序关联管理
    const authcode34 = 34;//	微信商品库管理
    const authcode35 = 35;//	微信卡路里
    const authcode44 = 44;//	好物圈
    const authcode46 = 46;//	微信一物一码
    const authcode47 = 47;//	微信财政电子票据
    const authcode54 = 54;//	服务号对话管理
    const authcode66 = 66;//	微信服务市场管理
    const authcode89 = 89;//	服务号订阅通知
    const authcode121 = 121;//	公众号购物订单
    const authcode17 = 17;//	获取小程序码
    const authcode18 = 18;//	小程序开发与数据分析
    const authcode19 = 19;//	小程序客服管理
    const authcode25 = 25;//	开放平台账号管理
    const authcode30 = 30;//	小程序基本信息管理
    const authcode31 = 31;//	小程序认证名称检测
    const authcode36 = 36;//	微信卡路里管理
    const authcode37 = 37;//	附近的小程序管理
    const authcode40 = 40;//	小程序插件管理
    const authcode41 = 41;//	好物圈管理
    const authcode45 = 45;//	微信物流服务
    const authcode48 = 48;//	微信财政电子票据管理
    const authcode49 = 49;//	小程序云开发管理
    const authcode51 = 51;//	小程序即时配送
    const authcode52 = 52;//	小程序直播管理
    const authcode65 = 65;//	小程序广告管理
    const authcode67 = 67;//	微信服务市场管理
    const authcode70 = 70;//	标准版交易组件商品管理
    const authcode71 = 71;//	标准版交易组件订单物流与售后管理
    const authcode73 = 73;//	标准版交易组件接入
    const authcode76 = 76;//	小程序违规与交易投诉管理
    const authcode81 = 81;//	试用小程序快速认证
    const authcode84 = 84;//	标准版交易组件优惠券管理
    const authcode85 = 85;//	自定义版交易组件管理
    const authcode86 = 86;//	小商店装修
    const authcode88 = 88;//	小程序链接管理
    const authcode93 = 93;//	小程序联盟管理
    const authcode99 = 99;//	云开发短信服务
    const authcode102 = 102;//	云开发微信支付
    const authcode104 = 104;//	标准版组件资金链路
    const authcode105 = 105;//	城市服务
    const authcode112 = 112;//	红包封面管理
    const authcode116 = 116;//	获取自定义版交易组件数据
    const authcode118 = 118;//	硬件服务
    const authcode119 = 119;//	小程序支付管理服务
    const authcode120 = 120;//	小程序购物订单
    const authcode129 = 129;//	视频号小店商品管理
    const authcode130 = 130;//	视频号小店物流管理
    const authcode131 = 131;//	视频号小店订单与售后管理
    const authcode132 = 132;//	视频号小店优惠券管理
    const authcode135 = 135;//	流量主代运营权限集
    const authcode139 = 139;//	小程序运费险
    const authcode142 = 142;//	小程序发货管理服务
    const authcode144 = 144;//	小程序学生认证权限集
    const authcode151 = 151;//	小程序交易保障
    const authcode153 = 153;//	微短剧小程序资源管理
    const authcode157 = 157;//	小程序虚拟支付管理权限
    const authcode161 = 161;//	微信客服管理

    public static $messageCategory = 'App';

    protected static $list = [
        self::authcode1 => '消息管理',
        self::authcode2 => '用户管理',
        self::authcode3 => '账号服务',
        self::authcode4 => '网页服务',
        self::authcode5 => '微信小店',
        self::authcode6 => '微信多客服',
        self::authcode7 => '群发与通知',
        self::authcode8 => '微信卡券',
        self::authcode9 => '微信扫一扫',
        self::authcode10 => '微信连WIFI',
        self::authcode11 => '素材管理',
        self::authcode12 => '微信摇周边',
        self::authcode13 => '微信门店',
        self::authcode15 => '菜单管理',
        self::authcode22 => '城市服务',
        self::authcode23 => '广告管理',
        self::authcode24 => '开放平台账号管理',
        self::authcode26 => '微信电子发票',
        self::authcode27 => '快速注册小程序',
        self::authcode33 => '小程序关联管理',
        self::authcode34 => '微信商品库管理',
        self::authcode35 => '微信卡路里',
        self::authcode44 => '好物圈',
        self::authcode46 => '微信一物一码',
        self::authcode47 => '微信财政电子票据',
        self::authcode54 => '服务号对话管理',
        self::authcode66 => '微信服务市场管理',
        self::authcode89 => '服务号订阅通知',
        self::authcode121 => '公众号购物订单',
        self::authcode17 => '获取小程序码',
        self::authcode18 => '小程序开发与数据分析',
        self::authcode19 => '小程序客服管理',
        self::authcode25 => '开放平台账号管理',
        self::authcode30 => '小程序基本信息管理',
        self::authcode31 => '小程序认证名称检测',
        self::authcode36 => '微信卡路里管理',
        self::authcode37 => '附近的小程序管理',
        self::authcode40 => '小程序插件管理',
        self::authcode41 => '好物圈管理',
        self::authcode45 => '微信物流服务',
        self::authcode48 => '微信财政电子票据管理',
        self::authcode49 => '小程序云开发管理',
        self::authcode51 => '小程序即时配送',
        self::authcode52 => '小程序直播管理',
        self::authcode65 => '小程序广告管理',
        self::authcode67 => '微信服务市场管理',
        self::authcode70 => '标准版交易组件商品管理',
        self::authcode71 => '标准版交易组件订单物流与售后管',
        self::authcode73 => '标准版交易组件接入',
        self::authcode76 => '小程序违规与交易投诉管理',
        self::authcode81 => '试用小程序快速认证',
        self::authcode84 => '标准版交易组件优惠券管理',
        self::authcode85 => '自定义版交易组件管理',
        self::authcode86 => '小商店装修',
        self::authcode88 => '小程序链接管理',
        self::authcode93 => '小程序联盟管理',
        self::authcode99 => '云开发短信服务',
        self::authcode102 => '云开发微信支付',
        self::authcode104 => '标准版组件资金链路',
        self::authcode105 => '城市服务',
        self::authcode112 => '红包封面管理',
        self::authcode116 => '获取自定义版交易组件数',
        self::authcode118 => '硬件服务',
        self::authcode119 => '小程序支付管理服务',
        self::authcode120 => '小程序购物订单',
        self::authcode129 => '视频号小店商品管理',
        self::authcode130 => '视频号小店物流管理',
        self::authcode131 => '视频号小店订单与售后管',
        self::authcode132 => '视频号小店优惠券管理',
        self::authcode135 => '流量主代运营权限集',
        self::authcode139 => '小程序运费险',
        self::authcode142 => '小程序发货管理服务',
        self::authcode144 => '小程序学生认证权限集',
        self::authcode151 => '小程序交易保障',
        self::authcode153 => '微短剧小程序资源管理',
        self::authcode157 => '小程序虚拟支付管理权限',
        self::authcode161 => '微信客服管理'
    ];

}