<?php

use yii\db\Migration;

class m240417_014729_diandi_place_room_type extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%diandi_place_room_type}}', [
            'id' => "int(11) NOT NULL AUTO_INCREMENT",
            'bloc_id' => "int(11) NULL DEFAULT '0' COMMENT '公司ID'",
            'store_id' => "int(11) NULL COMMENT '商户ID'",
            'hotel_id' => "int(11) NULL COMMENT '酒店ID'",
            'type_id' => "int(11) NULL COMMENT '业务类型'",
            'room_type' => "int(11) NOT NULL DEFAULT '0' COMMENT '全局房型'",
            'title' => "varchar(255) NULL DEFAULT '' COMMENT '房型名称'",
            'thumb' => "varchar(255) NULL DEFAULT '' COMMENT '房间主图'",
            'oprice' => "decimal(11,2) NULL DEFAULT '0.00' COMMENT '原价'",
            'cprice' => "decimal(11,2) NULL DEFAULT '0.00' COMMENT '现价'",
            'mprice' => "decimal(11,2) NULL DEFAULT '0.00' COMMENT '会员价'",
            'thumbs' => "text NULL COMMENT '房间相册'",
            'device' => "text NULL COMMENT '服务设施'",
            'is_suite' => "int(11) NULL DEFAULT '0' COMMENT '是否是套房'",
            'area' => "varchar(255) NULL DEFAULT '' COMMENT '面积'",
            'room_num' => "int(11) NULL COMMENT '几室'",
            'toilet_num' => "int(11) NULL COMMENT '几卫'",
            'floor' => "varchar(255) NULL DEFAULT '' COMMENT '楼层'",
            'bed_children' => "int(11) NULL COMMENT '儿童床位数'",
            'bed_adult' => "int(11) NULL COMMENT '成人床位数'",
            'bed_guest' => "int(11) NULL DEFAULT '0' COMMENT '客人床位数'",
            'bed' => "int(11) NULL COMMENT '床位数'",
            'cleaning_fee' => "decimal(11,2) NULL DEFAULT '0.00' COMMENT '清洁费'",
            'server_fee' => "decimal(11,2) NULL COMMENT '服务费'",
            'persons' => "int(11) NULL DEFAULT '0' COMMENT '最多容纳人数'",
            'bedadd' => "varchar(30) NULL DEFAULT '' COMMENT '是否可加床'",
            'isshow' => "int(11) NULL DEFAULT '0' COMMENT '是否显示'",
            'sales' => "text NULL COMMENT '销售数量'",
            'displayorder' => "int(11) NULL DEFAULT '0' COMMENT '排序'",
            'area_show' => "int(11) NULL DEFAULT '0' COMMENT '是否显示具体位置'",
            'floor_show' => "int(11) NULL DEFAULT '0' COMMENT '是否显示楼层'",
            'smoke_show' => "int(11) NULL DEFAULT '0' COMMENT '是否显示抽烟'",
            'bed_show' => "int(11) NULL DEFAULT '0' COMMENT '是否添加床位'",
            'persons_show' => "int(11) NULL COMMENT '是否显示添加人数'",
            'bedadd_show' => "int(11) NULL DEFAULT '0' COMMENT '是否显示添加床位'",
            'score' => "int(11) NULL DEFAULT '0' COMMENT '订房积分'",
            'breakfast' => "tinyint(3) NULL DEFAULT '0' COMMENT '0无早 1单早 2双早'",
            'language' => "tinyint(4) NOT NULL DEFAULT '0' COMMENT '语言类型标志/默认中文0'",
            'free_cancel' => "tinyint(4) NULL DEFAULT '0' COMMENT '是否免费取下1是0否'",
            'checkIn_start' => "varchar(30) NULL COMMENT '入住开始时间'",
            'checkIn_end' => "varchar(30) NULL COMMENT '入住结束时间'",
            'cancel_start' => "varchar(30) NULL COMMENT '取消开始时间'",
            'cancel_end' => "varchar(30) NULL COMMENT '退房结束时间'",
            'remark' => "text NULL COMMENT '备注'",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=MyISAM  DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC");
        
        /* 索引设置 */
        
        
        /* 表数据 */
        $this->insert('{{%diandi_place_room_type}}',['id'=>'1','bloc_id'=>'93','store_id'=>'2','hotel_id'=>'106','type_id'=>'5','room_type'=>'1','title'=>'茶室','thumb'=>'202311/19/51fe4f4d-714d-31e0-9208-fa5764453bba.jpg','oprice'=>'2.00','cprice'=>'2.00','mprice'=>'2.00','thumbs'=>'s:5:"false";','device'=>'','is_suite'=>'0','area'=>'2','room_num'=>'1','toilet_num'=>'11','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'2','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'12','bedadd'=>'1','isshow'=>'1','sales'=>'1','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'11','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'14:10:38','cancel_end'=>'15:10:38','remark'=>'']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'2','bloc_id'=>'91','store_id'=>'153','hotel_id'=>NULL,'type_id'=>'15','room_type'=>'15','title'=>'双床房房型','thumb'=>'','oprice'=>'1.00','cprice'=>'2.00','mprice'=>'3.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'7','bedadd'=>NULL,'isshow'=>'0','sales'=>'4','displayorder'=>'5','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'1','score'=>'8','breakfast'=>'0','language'=>'0','free_cancel'=>'1','checkIn_start'=>'05:28:00','checkIn_end'=>'07:28:00','cancel_start'=>'09:28:00','cancel_end'=>'10:28:00','remark'=>'2121']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'3','bloc_id'=>'98','store_id'=>'297','hotel_id'=>'112','type_id'=>'1','room_type'=>'15','title'=>'南京酒店房型A-大床房','thumb'=>'202402/03/08d3a2c9-7d16-3130-9dcc-efa2d70a7c7d.jpg','oprice'=>'1.00','cprice'=>'1.00','mprice'=>'1.00','thumbs'=>'a:2:{i:0;s:50:"202402/03/c8709889-3132-35cd-916b-780f6bcbacf8.jpg";i:1;s:50:"202402/03/d776bb40-57b1-3635-86bc-9d8786325c25.jpg";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>'0','toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'1','bedadd'=>NULL,'isshow'=>'0','sales'=>'1','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'1','breakfast'=>'1','language'=>'0','free_cancel'=>'1','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'20:32:08','cancel_end'=>'21:32:08','remark'=>'']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'4','bloc_id'=>'98','store_id'=>'298','hotel_id'=>'113','type_id'=>'3','room_type'=>'1','title'=>'民宿房型A-单间','thumb'=>'202402/03/3d299cbd-771e-36e1-9334-1f0a05640474.jpg','oprice'=>'2.00','cprice'=>'2.00','mprice'=>'1.00','thumbs'=>'a:2:{i:0;s:50:"202402/03/cef82baf-d133-3e72-8615-64b759923c33.jpg";i:1;s:50:"202402/03/42b039c5-b1ad-3f70-b776-7a264211f773.jpg";}','device'=>NULL,'is_suite'=>'0','area'=>'2','room_num'=>'1','toilet_num'=>'11','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'2','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'1','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'1','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'22:06:07','cancel_end'=>'23:06:07','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'5','bloc_id'=>'106','store_id'=>'299','hotel_id'=>'114','type_id'=>'3','room_type'=>'1','title'=>'河北测试房型','thumb'=>'202402/10/10d7c5d1-34a0-372e-8abd-578f8b3c1808.png','oprice'=>'1.00','cprice'=>'1.00','mprice'=>'1.00','thumbs'=>'a:1:{i:0;s:50:"202402/10/ecccbd61-3ac1-38b6-8bac-84d8d37eae75.png";}','device'=>NULL,'is_suite'=>'0','area'=>'2','room_num'=>'1','toilet_num'=>'11','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'1','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'1','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'11','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'19:19:06','cancel_end'=>'20:19:06','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'6','bloc_id'=>'107','store_id'=>'300','hotel_id'=>'115','type_id'=>'1','room_type'=>'2','title'=>'大床房','thumb'=>'202402/16/951bac21-9b7a-34e2-a9ee-8b2c5973ceef.jpg','oprice'=>'1.00','cprice'=>'1.00','mprice'=>'1.00','thumbs'=>'a:1:{i:0;s:50:"202402/16/3505aa4f-e30a-3545-aa76-9b2a59569417.jpg";}','device'=>NULL,'is_suite'=>'0','area'=>'1','room_num'=>'11','toilet_num'=>'1','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'1','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'1','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'11','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'16:09:33','cancel_end'=>'17:09:33','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'7','bloc_id'=>'38','store_id'=>'302','hotel_id'=>'116','type_id'=>'1','room_type'=>'1','title'=>'双床房','thumb'=>'202402/16/b443c4a4-d3c3-3eda-8445-136c6ff59b08.jpg','oprice'=>'2.00','cprice'=>'2.00','mprice'=>'2.00','thumbs'=>'a:1:{i:0;s:50:"202402/16/776c667f-e1ec-3567-b8f0-e165349aad67.jpg";}','device'=>NULL,'is_suite'=>'0','area'=>'2','room_num'=>'1','toilet_num'=>'1','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'2','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'11','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'1','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'17:32:56','cancel_end'=>'18:32:56','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'8','bloc_id'=>'114','store_id'=>'303','hotel_id'=>'117','type_id'=>'5','room_type'=>'1','title'=>'茶室','thumb'=>'202402/19/3988d9f0-136b-33ce-b72e-c7f2399fe7cd.png','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:1:{i:0;s:50:"202402/19/0b496793-a729-3a74-a5bc-5ec820b142ef.png";}','device'=>'','is_suite'=>'0','area'=>'5','room_num'=>'1','toilet_num'=>'11','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'5','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'1','displayorder'=>'11','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'11','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'09:01:40','cancel_end'=>'10:01:40','remark'=>'']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'9','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'3','title'=>'双床房','thumb'=>'','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'05:28:00','checkIn_end'=>'05:28:00','cancel_start'=>'05:28:00','cancel_end'=>'05:28:00','remark'=>'2']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'10','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'15','title'=>'测试双床房','thumb'=>'','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'5','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'5','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'5']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'11','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'18','title'=>'大床房','thumb'=>'','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'55.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'5','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'5','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'5']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'12','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'15','title'=>'scc','thumb'=>'','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'5','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'13','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'18','title'=>'jiud ','thumb'=>'','oprice'=>'55.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'555','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'14','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'26','title'=>'这个是个豪包','thumb'=>'','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'15','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'26','title'=>'棋牌室房型','thumb'=>'','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'5','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'555','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'16','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'3','room_type'=>'26','title'=>'棋牌室房型','thumb'=>'','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'5','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'555','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'17','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'18','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'19','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'20','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'21','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'22','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'23','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'24','bloc_id'=>'98','store_id'=>'296','hotel_id'=>NULL,'type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'25','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'6','room_type'=>'28','title'=>'棋牌室测试','thumb'=>'202402/20/c98018f1-1f32-3da7-b98d-b2b41c4342a4.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/65e53d54-3a88-3fc9-8722-5c4d0a81a0ae.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'5','bedadd'=>NULL,'isshow'=>'0','sales'=>'55','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'55','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'55']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'26','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'5','room_type'=>'39','title'=>'豪包茶室','thumb'=>'202402/20/e6c38ff0-b744-3760-a17e-49d4c1944a91.png','oprice'=>'5.00','cprice'=>'5.00','mprice'=>'55.00','thumbs'=>'a:1:{i:0;s:50:"202402/20/b0f9f3ea-8981-3929-a5f0-530659879f23.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>'0','toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'5','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'5','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'5']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'27','bloc_id'=>'98','store_id'=>'296','hotel_id'=>'111','type_id'=>'2','room_type'=>'30','title'=>'民宿一室','thumb'=>'202402/21/8ab08f8e-8ce4-35cd-9677-0d6c9276b0d8.png','oprice'=>'5.00','cprice'=>'55.00','mprice'=>'5.00','thumbs'=>'a:1:{i:0;s:50:"202402/21/c4ba08ec-05a5-3ca8-9554-201316a9527d.png";}','device'=>NULL,'is_suite'=>'0','area'=>NULL,'room_num'=>NULL,'toilet_num'=>NULL,'floor'=>NULL,'bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>NULL,'bed'=>NULL,'cleaning_fee'=>NULL,'server_fee'=>NULL,'persons'=>'55','bedadd'=>NULL,'isshow'=>'0','sales'=>'5','displayorder'=>'55','area_show'=>'0','floor_show'=>'0','smoke_show'=>'0','bed_show'=>'0','persons_show'=>'0','bedadd_show'=>'0','score'=>'5','breakfast'=>'0','language'=>'0','free_cancel'=>'0','checkIn_start'=>'','checkIn_end'=>'','cancel_start'=>'','cancel_end'=>'','remark'=>'2332']);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'28','bloc_id'=>'144','store_id'=>'309','hotel_id'=>'122','type_id'=>'6','room_type'=>'3','title'=>'A型','thumb'=>'202403/21/352f6f4a-ef14-3fd3-b29d-e72af20bcc6e.png','oprice'=>'0.00','cprice'=>'0.00','mprice'=>'0.00','thumbs'=>'a:1:{i:0;s:50:"202403/21/1d407088-6007-35a5-b050-34416f892cb6.png";}','device'=>NULL,'is_suite'=>'0','area'=>'','room_num'=>NULL,'toilet_num'=>NULL,'floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'1','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'6','bedadd'=>'1','isshow'=>'1','sales'=>NULL,'displayorder'=>'0','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'0','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'12:20:34','cancel_end'=>'13:20:34','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'29','bloc_id'=>'159','store_id'=>'308','hotel_id'=>'124','type_id'=>'5','room_type'=>'1','title'=>'茶室','thumb'=>'202403/28/0d63fadc-f061-3932-a759-9e0f5f0042ea.jpg','oprice'=>'1.00','cprice'=>'1.00','mprice'=>'1.00','thumbs'=>'a:1:{i:0;s:50:"202403/28/e89ac7c2-f838-3355-ac26-75b565154c9d.jpg";}','device'=>NULL,'is_suite'=>'0','area'=>'1','room_num'=>'11','toilet_num'=>'1','floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'1','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'1','bedadd'=>'1','isshow'=>'1','sales'=>'11','displayorder'=>'1','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'1','breakfast'=>'1','language'=>'1','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'09:08:00','cancel_end'=>'10:08:00','remark'=>NULL]);
        $this->insert('{{%diandi_place_room_type}}',['id'=>'30','bloc_id'=>'189','store_id'=>'310','hotel_id'=>'125','type_id'=>'1','room_type'=>'2','title'=>'牛逼房间','thumb'=>'牛逼房间','oprice'=>'999.00','cprice'=>'9999.00','mprice'=>'99.00','thumbs'=>'a:0:{}','device'=>NULL,'is_suite'=>'0','area'=>'99','room_num'=>NULL,'toilet_num'=>NULL,'floor'=>'','bed_children'=>NULL,'bed_adult'=>NULL,'bed_guest'=>'0','bed'=>'2','cleaning_fee'=>'0.00','server_fee'=>NULL,'persons'=>'0','bedadd'=>'1','isshow'=>'1','sales'=>NULL,'displayorder'=>'0','area_show'=>'1','floor_show'=>'1','smoke_show'=>'1','bed_show'=>'1','persons_show'=>'1','bedadd_show'=>'0','score'=>'0','breakfast'=>'1','language'=>'0','free_cancel'=>'1','checkIn_start'=>NULL,'checkIn_end'=>NULL,'cancel_start'=>'16:19:19','cancel_end'=>'17:19:19','remark'=>NULL]);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%diandi_place_room_type}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

