<?php return array(
    0 =>
        array(
            'name' => '房源',
            'route' => '/diandi_place/place/brand/index.vue',
            'order' => 3,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 1,
            'icon' => 'hotel-Property-Management',
            'is_sys' => 0,
            'module_name' => 'diandi_place',
            'is_show' => 0,
            'router' =>
                array(
                    'name' => '/diandi_place/place/brand/index.vue',
                    'item_id' => NULL,
                    'route_name' => 'diandi_place-place-brand-index',
                    'is_sys' => 0,
                    'route_type' => 1,
                    'description' => '',
                    'title' => '品牌管理',
                    'pid' => 0,
                    'data' => '',
                    'module_name' => 'diandi_place',
                    'item' => NULL,
                ),
            'level' => 3,
            'child' =>
                array(
                    0 =>
                        array(
                            'name' => '房态维护',
                            'route' => '/main/index.vue',
                            'order' => 2,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 3,
                            'icon' => 'hotel-order-management',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/main/index.vue',
                                    'item_id' => 13506,
                                    'route_name' => 'main-index',
                                    'is_sys' => 1,
                                    'route_type' => 0,
                                    'description' => '',
                                    'title' => 'main入口',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'system',
                                    'item' =>
                                        array(
                                            'name' => '/main/index.vue',
                                            'is_sys' => 1,
                                            'permission_type' => 0,
                                            'description' => NULL,
                                            'rule_name' => 0,
                                            'parent_id' => 0,
                                            'permission_level' => 0,
                                            'data' => NULL,
                                            'module_name' => 'sys',
                                        ),
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '房态维护',
                                            'route' => '/diandi_place/room/room-status/index.vue',
                                            'order' => 2,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 5,
                                            'icon' => 'sys-Merchant-Management',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 0,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/room-status/index.vue',
                                                    'item_id' => 15377,
                                                    'route_name' => 'diandi_place-room-room-status-index',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '房态维护',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '房价维护',
                                            'route' => '/diandi_place/room/room-price/index.vue',
                                            'order' => 2,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 5,
                                            'icon' => 'tea-recharge-activity',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 0,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/room-price/index.vue',
                                                    'item_id' => 15374,
                                                    'route_name' => '/diandi_place/room/room-price/index.vue',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '房间价格',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    2 =>
                                        array(
                                            'name' => '房间服务',
                                            'route' => '/diandi_place/room/server/index.vue',
                                            'order' => 2,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 5,
                                            'icon' => 'sys-organizational-structure',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 0,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/server/index.vue',
                                                    'item_id' => 15414,
                                                    'route_name' => 'diandi-place-room-server-index',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '房间服务',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    1 =>
                        array(
                            'name' => '房间管理',
                            'route' => '/diandi_place/room/list/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Hotel-Advertising',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/room/list/index.vue',
                                    'item_id' => 15404,
                                    'route_name' => 'diandi-place-room-list-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '房间管理',
                                    'pid' => 0,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '房间管理创建',
                                            'route' => '/diandi_place/room/list/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/list/create.vue',
                                                    'item_id' => 15369,
                                                    'route_name' => 'diandi_place-room-list-create',
                                                    'is_sys' => 1,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '房间管理修改',
                                            'route' => '/diandi_place/room/list/update.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/list/update.vue',
                                                    'item_id' => 15370,
                                                    'route_name' => 'diandi_place-room-list-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    2 =>
                        array(
                            'name' => '人员管理',
                            'route' => '/diandi_place/room/persion-type/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-personnel-management',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/room/persion-type/index.vue',
                                    'item_id' => 15371,
                                    'route_name' => 'diandi_place-room-persion-type-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '人员类型',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '人员类型创建',
                                            'route' => '/diandi_place/room/persion-type/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/persion-type/create.vue',
                                                    'item_id' => 15372,
                                                    'route_name' => 'diandi_place-room-persion-type-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '人员类型修改',
                                            'route' => '/diandi_place/room/persion-type/update.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/persion-type/update.vue',
                                                    'item_id' => 15373,
                                                    'route_name' => 'diandi_place-room-persion-type-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    3 =>
                        array(
                            'name' => '房间相册',
                            'route' => '/diandi_place/room/roompslide/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Room-Album',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/room/roompslide/index.vue',
                                    'item_id' => 15411,
                                    'route_name' => 'diandi-place-room-roompslide-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '房间相册',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '房间相册创建',
                                            'route' => '/diandi_place/room/roompslide/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => NULL,
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' => NULL,
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '房间相册修改',
                                            'route' => '/diandi_place/room/roompslide/update.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/roompslide/update.vue',
                                                    'item_id' => 15413,
                                                    'route_name' => 'diandi-place-room-roompslide-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    4 =>
                        array(
                            'name' => '房型管理',
                            'route' => '/diandi_place/room/room-type/index.vue',
                            'order' => 1,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Property-Management',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/room/room-type/index.vue',
                                    'item_id' => 15578,
                                    'route_name' => 'diandi-place-room-type-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '房型列表',
                                    'title' => '房型管理',
                                    'pid' => NULL,
                                    'data' => NULL,
                                    'module_name' => 'diandi_place',
                                    'item' =>
                                        array(
                                            'name' => '/diandi_tea/config/config-house.vue',
                                            'is_sys' => 0,
                                            'permission_type' => 0,
                                            'description' => NULL,
                                            'rule_name' => 0,
                                            'parent_id' => 0,
                                            'permission_level' => 0,
                                            'data' => NULL,
                                            'module_name' => 'diandi_tea',
                                        ),
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '新建房型',
                                            'route' => '/diandi_place/room/room-type/create.vue',
                                            'order' => 1,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/room-type/create.vue',
                                                    'item_id' => 15579,
                                                    'route_name' => 'diandi-place-room-type-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 2,
                                                    'description' => '',
                                                    'title' => '新增房型',
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' =>
                                                        array(
                                                            'name' => '/diandi_tea/config/config-house-create.vue',
                                                            'is_sys' => 0,
                                                            'permission_type' => 0,
                                                            'description' => NULL,
                                                            'rule_name' => 0,
                                                            'parent_id' => 0,
                                                            'permission_level' => 0,
                                                            'data' => NULL,
                                                            'module_name' => 'diandi_tea',
                                                        ),
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '编辑房型',
                                            'route' => '/diandi_place/room/room-type/update.vue',
                                            'order' => 1,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/room/room-type/update.vue',
                                                    'item_id' => 15580,
                                                    'route_name' => 'diandi-place-room-type-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 2,
                                                    'description' => '',
                                                    'title' => '修改房型',
                                                    'pid' => NULL,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' =>
                                                        array(
                                                            'name' => '/diandi_tea/config/config-house-update.vue',
                                                            'is_sys' => 0,
                                                            'permission_type' => 0,
                                                            'description' => NULL,
                                                            'rule_name' => 0,
                                                            'parent_id' => 0,
                                                            'permission_level' => 0,
                                                            'data' => NULL,
                                                            'module_name' => 'diandi_tea',
                                                        ),
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                ),
        ),
    1 =>
        array(
            'name' => '场所',
            'route' => '/diandi_place/place/list/index.vue',
            'order' => 2,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 1,
            'icon' => 'integral-express-delivery',
            'is_sys' => 0,
            'module_name' => 'diandi_place',
            'is_show' => 0,
            'router' =>
                array(
                    'name' => '/diandi_place/place/list/index.vue',
                    'item_id' => NULL,
                    'route_name' => 'diandi_place-place-list-index',
                    'is_sys' => 0,
                    'route_type' => 1,
                    'description' => '',
                    'title' => '酒店管理',
                    'pid' => 0,
                    'data' => '',
                    'module_name' => 'diandi_place',
                    'item' => NULL,
                ),
            'level' => 3,
            'child' =>
                array(
                    0 =>
                        array(
                            'name' => '服务管理',
                            'route' => '/diandi_place/place/server/index.vue',
                            'order' => 3,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'sys-system',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/server/index.vue',
                                    'item_id' => 15389,
                                    'route_name' => 'diandi-place-place-server-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '服务管理',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '服务管理创建',
                                            'route' => '/diandi_place/place/server/create.vue',
                                            'order' => 3,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => NULL,
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' => NULL,
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '服务管理修改',
                                            'route' => '/diandi_place/place/server/update.vue',
                                            'order' => 3,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => NULL,
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' => NULL,
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    1 =>
                        array(
                            'name' => '楼层管理',
                            'route' => '/diandi_place/place/tier/index.vue',
                            'order' => 2,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'sys-Company-management',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/tier/index.vue',
                                    'item_id' => 15425,
                                    'route_name' => 'diandi_place-place-tier-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '楼层管理',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '创建楼层管理',
                                            'route' => '/diandi_place/place/tier/create.vue',
                                            'order' => 1,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/tier/create.vue',
                                                    'item_id' => 15426,
                                                    'route_name' => 'diandi_place-place-tier-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '创建楼层管理',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '修改楼层管理',
                                            'route' => '/diandi_place/place/tier/update.vue',
                                            'order' => 1,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/tier/update.vue',
                                                    'item_id' => 15427,
                                                    'route_name' => 'diandi_place-place-tier-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '修改楼层管理',
                                                    'pid' => NULL,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    2 =>
                        array(
                            'name' => '经营场所',
                            'route' => '/diandi_place/place/list/index.vue',
                            'order' => 1,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'integral-express-delivery',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/list/index.vue',
                                    'item_id' => NULL,
                                    'route_name' => 'diandi_place-place-list-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '酒店管理',
                                    'pid' => 0,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '房源管理创建',
                                            'route' => '/diandi_place/place/list/create.vue',
                                            'order' => 2,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/list/create.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-list-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '房源管理修改',
                                            'route' => '/diandi_place/place/list/update.vue',
                                            'order' => 2,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/list/update.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-list-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                ),
        ),
    2 =>
        array(
            'name' => '房东',
            'route' => '/diandi_place/vip/member/index.vue',
            'order' => 6,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 1,
            'icon' => 'hotel-personnel-management',
            'is_sys' => 0,
            'module_name' => 'diandi_place',
            'is_show' => 1,
            'router' =>
                array(
                    'name' => '/diandi_place/vip/member/index.vue',
                    'item_id' => 15405,
                    'route_name' => 'diandi-place-vip-member-index',
                    'is_sys' => 0,
                    'route_type' => 1,
                    'description' => '',
                    'title' => '会员管理',
                    'pid' => NULL,
                    'data' => '',
                    'module_name' => 'diandi_place',
                    'item' => NULL,
                ),
            'level' => 3,
            'child' =>
                array(
                    0 =>
                        array(
                            'name' => '管理员',
                            'route' => '/diandi_place/vip/member/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => '',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/vip/member/index.vue',
                                    'item_id' => 15405,
                                    'route_name' => 'diandi-place-vip-member-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '会员管理',
                                    'pid' => NULL,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '管理员创建',
                                            'route' => '/diandi_place/vip/member/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/vip/member/create.vue',
                                                    'item_id' => 15406,
                                                    'route_name' => 'diandi-place-vip-member-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '管理员修改',
                                            'route' => '/diandi_place/vip/member/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/vip/member/create.vue',
                                                    'item_id' => 15406,
                                                    'route_name' => 'diandi-place-vip-member-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                ),
        ),
    3 =>
        array(
            'name' => '首页',
            'route' => '/diandi_place/default/index.vue',
            'order' => 1,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 1,
            'icon' => 'hotel-home-page',
            'is_sys' => 0,
            'module_name' => 'diandi_place',
            'is_show' => 0,
            'router' =>
                array(
                    'name' => '/diandi_place/default/index.vue',
                    'item_id' => NULL,
                    'route_name' => 'diandi_place-default-index',
                    'is_sys' => 0,
                    'route_type' => 1,
                    'description' => NULL,
                    'title' => NULL,
                    'pid' => 0,
                    'data' => NULL,
                    'module_name' => 'diandi_place',
                    'item' => NULL,
                ),
            'level' => 3,
            'child' =>
                array(
                    0 =>
                        array(
                            'name' => '首页',
                            'route' => '/diandi_place/default/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-home-page',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/default/index.vue',
                                    'item_id' => NULL,
                                    'route_name' => 'diandi_place-default-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => NULL,
                                    'title' => NULL,
                                    'pid' => 0,
                                    'data' => NULL,
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                        ),
                ),
        ),
    4 =>
        array(
            'name' => '配套',
            'route' => '/diandi_place/vip/member/create.vue',
            'order' => 6,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 1,
            'icon' => 'hotel-Supporting-facilities',
            'is_sys' => 0,
            'module_name' => 'diandi_place',
            'is_show' => 0,
            'router' =>
                array(
                    'name' => '/diandi_place/vip/member/create.vue',
                    'item_id' => 15406,
                    'route_name' => 'diandi-place-vip-member-create',
                    'is_sys' => 0,
                    'route_type' => 1,
                    'description' => '',
                    'title' => '',
                    'pid' => 0,
                    'data' => '',
                    'module_name' => 'diandi_place',
                    'item' => NULL,
                ),
            'level' => 3,
            'child' =>
                array(
                    0 =>
                        array(
                            'name' => '品牌管理',
                            'route' => '/diandi_place/place/brand/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Room-advertising-space',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/brand/index.vue',
                                    'item_id' => NULL,
                                    'route_name' => 'diandi_place-place-brand-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '品牌管理',
                                    'pid' => 0,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '品牌管理创建',
                                            'route' => '/diandi_place/place/brand/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/brand/create.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-brand-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '品牌管理修改',
                                            'route' => '/diandi_place/place/brand/update.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/brand/update.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-brand-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => '',
                                                    'title' => '',
                                                    'pid' => 0,
                                                    'data' => '',
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    1 =>
                        array(
                            'name' => '配置',
                            'route' => '/diandi_place/place/config/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Supporting-facilities',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/config/index.vue',
                                    'item_id' => NULL,
                                    'route_name' => 'diandi_place-place-config-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '配置管理',
                                    'pid' => 0,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '配置管理创建',
                                            'route' => '/diandi_place/place/config/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => NULL,
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' => NULL,
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '配置管理修改',
                                            'route' => '/diandi_place/place/config/update.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/config/update.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-config-update',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                    2 =>
                        array(
                            'name' => '地域管理',
                            'route' => '/diandi_place/place/region/index.vue',
                            'order' => 0,
                            'data' => NULL,
                            'type' => 'plugins',
                            'level_type' => 4,
                            'icon' => 'hotel-Regional-management',
                            'is_sys' => 0,
                            'module_name' => 'diandi_place',
                            'is_show' => 0,
                            'router' =>
                                array(
                                    'name' => '/diandi_place/place/region/index.vue',
                                    'item_id' => NULL,
                                    'route_name' => 'diandi_place-place-region-index',
                                    'is_sys' => 0,
                                    'route_type' => 1,
                                    'description' => '',
                                    'title' => '地域管理',
                                    'pid' => 0,
                                    'data' => '',
                                    'module_name' => 'diandi_place',
                                    'item' => NULL,
                                ),
                            'level' => 4,
                            'child' =>
                                array(
                                    0 =>
                                        array(
                                            'name' => '地域管理创建',
                                            'route' => '/diandi_place/place/region/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/region/create.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-region-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                    1 =>
                                        array(
                                            'name' => '地域管理修改',
                                            'route' => '/diandi_place/place/region/create.vue',
                                            'order' => 0,
                                            'data' => NULL,
                                            'type' => 'plugins',
                                            'level_type' => 6,
                                            'icon' => '',
                                            'is_sys' => 0,
                                            'module_name' => 'diandi_place',
                                            'is_show' => 1,
                                            'router' =>
                                                array(
                                                    'name' => '/diandi_place/place/region/create.vue',
                                                    'item_id' => NULL,
                                                    'route_name' => 'diandi_place-place-region-create',
                                                    'is_sys' => 0,
                                                    'route_type' => 1,
                                                    'description' => NULL,
                                                    'title' => NULL,
                                                    'pid' => 0,
                                                    'data' => NULL,
                                                    'module_name' => 'diandi_place',
                                                    'item' => NULL,
                                                ),
                                            'level' => 5,
                                        ),
                                ),
                        ),
                ),
        ),
);