<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2023-01-31 08:18:56
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2023-04-23 13:55:39
 */
namespace addons\diandi_place;
use addons\diandi_place\components\RoomInit;
use addons\diandi_place\events\LoginEvent;
use addons\diandi_place\models\enums\PlaceTypeEnums;
use addons\diandi_place\models\place\PlaceBrand;
use addons\diandi_place\models\place\PlaceList;
use admin\models\addons\models\Bloc;
use common\components\addons\AddonsModule;
use diandi\addons\models\BlocStore;
use Yii;
use yii\base\Event;
use yii\db\Exception;
/**
 * diandi_place module definition class.
 */
class admin extends AddonsModule
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = "addons\diandi_place\admin";
    /**
     * {@inheritdoc}
     */
    public function init(): void
    {
        parent::init();
        // 创建事件处理器实例
        $handler = new LoginEvent();
        // 监听用户登录成功事件
        Event::on(
            \yii\web\User::class,
            \yii\web\User::EVENT_AFTER_LOGIN,
            [$handler, 'handleAfterLogin']
        );
    }
    /**
     * @throws Exception
     */
    public function beforeAction($action): bool
    {
        $this->initBrand();
//        $this->initPlace(); 楼栋是客户的，不是分公司或商户的
        $this->initLandlord();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * 处理全局品牌数据与系统数据同步
     * @return void
     * @throws Exception
     */
    function initBrand(): void
    {
        $blocs = Bloc::find()->select(['bloc_id','business_name'])->asArray()->all();
        $brand = PlaceBrand::find()->indexBy('bloc_id')->asArray()->all();
        $data = [];
        foreach ($blocs as $item) {
            if (!key_exists($item['bloc_id'],$brand)){
//                需要写入
                $data[] = [$item['bloc_id'],$item['business_name'],0,1];
            }
        }
        if ($data){
            Yii::$app->db->createCommand()->batchInsert(PlaceBrand::tableName(), [
                'bloc_id',
                'title',
                'displayorder',
                'status'
            ], $data)->execute();
        }
    }
    private function initPlace()
    {
        $blocs = BlocStore::find()->asArray()->all();
        $place = PlaceList::find()->indexBy('bloc_id')->asArray()->all();
        $data = [];
        $type = PlaceTypeEnums::status1;
        foreach ($blocs as $item) {
            if (!key_exists($item['bloc_id'],$place)){
                //需要写入
                $data[] =[
                    $item['bloc_id'],
                    $item['store_id'],
                    $item['name'],
                    $item['address'],
                    $item['province'],
                    $item['city'],
                    $item['county'],
                    $item['status'],
                    $type
                ];
            }
        }
        if ($data){
            Yii::$app->db->createCommand()->batchInsert(PlaceList::tableName(), [
                'bloc_id',
                'store_id',
                'name',
                'address',
                'province',
                'city',
                'county',
                'status',
                'type',
            ], $data)->execute();
        }
    }
    /**
     * 初始化房东数据
     * @return void
     */
    private function initLandlord()
    {
    }
}
