<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2025-06-18 10:21:39
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2025-06-23 00:25:41
 */


namespace common\traits;

use common\helpers\ResultHelper;
use ddiot\http\AipBase;
use Exception;
use Yii;
use yii\db\StaleObjectException;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;

trait DdiotTrait
{
    private AipBase $client;
    private string $apiUrl;

    public function beforeAction($action): bool
    {
        $config = [
            'app_id' => env('DDIOT_APP_ID'),
            'app_secret' => env('DDIOT_APP_SECRET'),
            'project_sn' => env('DDIOT_PROJECT_SN'),
            'is_dev' => (int) env('DDIOT_PROJECT_DEV') === 1,
        ];
        $client = new AipBase('1.0.0');
        try {
            $client->setConfig($config);
            $this->apiUrl = parent::getDdiotApiUrl();
            $this->client = $client;
            return parent::beforeAction($action); // TODO: Change the autogenerated stub

        } catch (Exception $e) {
            throw new \yii\base\Exception($e->getMessage(), $e->getCode());
        }
    }


    /**
     * Lists all DeviceProtocol485 models.
     * @return array
     * @throws Exception
     */
    public function actionIndex(): array
    {
        $Res =  $this->client->post($this->apiUrl.'/getAll', Yii::$app->request->queryParams);
        return ResultHelper::json(200, '获取成功', $Res && is_array($Res)?$Res:[]);
    }

    /**
     * Displays a single DeviceProtocol485 model.
     * @param int $id
     * @return array
     * @throws NotFoundHttpException|Exception if the model cannot be found
     */
    public function actionView($id): array
    {
        $Res =  $this->client->get($this->apiUrl.'/getOne',[
            'id' => $id,
        ]);

        return ResultHelper::json(200, '获取成功',$Res??[]);
    }

    /**
     * Creates a new DeviceProtocol485 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return array
     * @throws Exception
     */
    public function actionCreate(): array
    {
        $data = Yii::$app->request->post();
        $Res =  $this->client->post($this->apiUrl.'/create',$data);
        return ResultHelper::json(200, '创建成功', $Res && is_array($Res)?$Res:[]);
    }

    /**
     * Updates an existing DeviceProtocol485 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id
     * @return array
     * @throws NotFoundHttpException|Exception if the model cannot be found
     */
    public function actionUpdate($id): array
    {
        $data = Yii::$app->request->post();
        $Res =  $this->client->post($this->apiUrl.'/update',$data);
        return ResultHelper::json(200, '编辑成功', $Res && is_array($Res)?$Res:[]);
    }

    /**
     * Deletes an existing WeihExhibitionServiceProvider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return array
     * @throws NotFoundHttpException if the model cannot be found
     * @throws StaleObjectException|Exception
     */
    public function actionDelete($id): array
    {
        $Res =  $this->client->post($this->apiUrl.'/delete',[
            'id' => $id,
        ]);
        return ResultHelper::json(200, '删除成功',$Res && is_array($Res)?$Res:[]);
    }


}