<?php
use yii\db\Migration;
class m240108_234139_diandi_place_list extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        /* 创建表 */
        $this->createTable('{{%diandi_place_list}}', [
            'id' => "int(11) NOT NULL AUTO_INCREMENT",
            'bloc_id' => "int(11) NULL DEFAULT '0' COMMENT '公司ID'",
            'store_id' => "int(11) NULL DEFAULT '0' COMMENT '商家ID'",
            'name' => "varchar(255) NULL DEFAULT '' COMMENT '酒店名称'",
            'lng' => "decimal(10,2) NULL COMMENT '经度'",
            'lat' => "decimal(10,2) NULL COMMENT '维度'",
            'is_show' => "int(11) NULL COMMENT '是否公开'",
            'address_show' => "int(11) NULL COMMENT '是否公开地址'",
            'type' => "int(11) NULL COMMENT '房源类型'",
            'address' => "varchar(255) NULL DEFAULT '' COMMENT '具体地址'",
            'location_p' => "int(11) NULL DEFAULT '0' COMMENT '省份'",
            'location_c' => "int(11) NULL DEFAULT '0' COMMENT '城市'",
            'location_a' => "int(11) NULL DEFAULT '0' COMMENT '区县'",
            'roomcount' => "int(11) NULL DEFAULT '0' COMMENT '房间总量'",
            'status' => "int(11) NULL DEFAULT '0' COMMENT '酒店状态'",
            'phone' => "varchar(255) NULL DEFAULT '' COMMENT '联系电话'",
            'mail' => "varchar(255) NULL DEFAULT '' COMMENT '联系邮箱'",
            'thumb' => "varchar(255) NULL DEFAULT '' COMMENT '酒店图片'",
            'description' => "text NULL COMMENT '酒店简介'",
            'content' => "text NULL COMMENT '酒店介绍'",
            'traffic' => "text NULL COMMENT '周边交通'",
            'thumbs' => "text NULL COMMENT '酒店相册'",
            'sales' => "text NULL",
            'displayorder' => "int(11) NULL DEFAULT '0' COMMENT '排序'",
            'comment_num' => "int(11) NULL DEFAULT '0' COMMENT '评价数量'",
            'comment_start' => "decimal(11,2) NULL COMMENT '评价星级'",
            'level' => "int(11) NULL DEFAULT '0' COMMENT '酒店星级'",
            'device' => "text NULL COMMENT '服务设施'",
            'brandid' => "int(11) NULL DEFAULT '0' COMMENT '所属品牌'",
            'language' => "tinyint(4) NOT NULL DEFAULT '0' COMMENT '语言类型标志/默认中文0'",
            'landlord_id' => "int(11) NULL DEFAULT '0' COMMENT '房东ID'",
            'apartment_type' => "int(11) NULL DEFAULT '0' COMMENT '公寓类型0整租1合租'",
            'create_time' => "datetime NULL",
            'update_time' => "datetime NULL",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='酒店主表'");
        /* 索引设置 */
        /* 表数据 */
        $this->insert('{{%diandi_place_list}}',['id'=>'106','bloc_id'=>'38','store_id'=>'2','name'=>'昆仑巢','lng'=>NULL,'lat'=>NULL,'is_show'=>NULL,'address_show'=>NULL,'type'=>'23','address'=>'北京市第十二中学','location_p'=>'0','location_c'=>'0','location_a'=>'0','roomcount'=>'15','status'=>'1','phone'=>'','mail'=>'12','thumb'=>'202311/19/bec2edc9-d90b-3be5-80ac-059292dbe4ff.jpg','description'=>'','content'=>'','traffic'=>'12','thumbs'=>'a:1:{i:0;s:50:"202311/19/9610290c-8d8e-3e58-abdf-8ab2d5606a36.jpg";}','sales'=>'55','displayorder'=>'12','comment_num'=>'0','comment_start'=>NULL,'level'=>'12','device'=>'12','brandid'=>'23','language'=>'0','landlord_id'=>'0','apartment_type'=>NULL,'create_time'=>'2023-11-19 13:59:35','update_time'=>'2023-11-19 20:23:45']);
        $this->insert('{{%diandi_place_list}}',['id'=>'107','bloc_id'=>'38','store_id'=>'2','name'=>'官方演示12','lng'=>NULL,'lat'=>NULL,'is_show'=>NULL,'address_show'=>NULL,'type'=>'23','address'=>'钟楼','location_p'=>'0','location_c'=>'0','location_a'=>'0','roomcount'=>'12','status'=>'1','phone'=>'','mail'=>'1','thumb'=>'202312/14/d6a59dc9-92f5-36b3-ae8c-8be734b8090a.png','description'=>'','content'=>'','traffic'=>'12','thumbs'=>'a:1:{i:0;s:50:"202312/14/77f3a574-30ed-37ec-9064-d30b03e25bea.png";}','sales'=>'12','displayorder'=>'1','comment_num'=>'0','comment_start'=>NULL,'level'=>'12','device'=>'1','brandid'=>'1','language'=>'0','landlord_id'=>'0','apartment_type'=>NULL,'create_time'=>'2023-12-14 12:09:25','update_time'=>'2023-12-14 14:06:15']);
        $this->insert('{{%diandi_place_list}}',['id'=>'108','bloc_id'=>'93','store_id'=>'3','name'=>'乐享棋牌室','lng'=>NULL,'lat'=>NULL,'is_show'=>NULL,'address_show'=>NULL,'type'=>'24','address'=>'泰华金贸国际-9号楼','location_p'=>'0','location_c'=>'0','location_a'=>'0','roomcount'=>'5','status'=>'1','phone'=>'','mail'=>'2192138785@qq.com','thumb'=>'202312/15/f633a63c-b7bd-3b52-b5cb-899ec5d8d0d7.jpg','description'=>NULL,'content'=>NULL,'traffic'=>'1','thumbs'=>'a:2:{i:0;s:50:"202312/15/c3abe642-4832-3826-a66a-1c87ff13e11f.jpg";i:1;s:50:"202312/15/d03647fb-aafe-3756-8de3-dfe1b2acf54d.jpg";}','sales'=>'12','displayorder'=>'1','comment_num'=>'0','comment_start'=>NULL,'level'=>'1','device'=>'1','brandid'=>'1','language'=>'0','landlord_id'=>'0','apartment_type'=>NULL,'create_time'=>'2023-12-15 10:08:30','update_time'=>'2023-12-15 10:08:30']);
        $this->insert('{{%diandi_place_list}}',['id'=>'109','bloc_id'=>'91','store_id'=>'256','name'=>'茶室','lng'=>NULL,'lat'=>NULL,'is_show'=>'1','address_show'=>'0','type'=>'23','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-25 15:41:23','update_time'=>'2023-12-25 15:41:23']);
        $this->insert('{{%diandi_place_list}}',['id'=>'110','bloc_id'=>'91','store_id'=>'153','name'=>'茶室1','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'23','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-25 15:46:32','update_time'=>'2023-12-25 15:46:32']);
        $this->insert('{{%diandi_place_list}}',['id'=>'111','bloc_id'=>'91','store_id'=>'258','name'=>'1','lng'=>NULL,'lat'=>NULL,'is_show'=>'1','address_show'=>'1','type'=>'18','address'=>'','location_p'=>'1','location_c'=>'110000','location_a'=>'110101','roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-28 17:01:01','update_time'=>'2023-12-28 17:01:01']);
        $this->insert('{{%diandi_place_list}}',['id'=>'112','bloc_id'=>'91','store_id'=>'259','name'=>'1','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-28 17:03:15','update_time'=>'2023-12-28 17:03:15']);
        $this->insert('{{%diandi_place_list}}',['id'=>'113','bloc_id'=>'91','store_id'=>'260','name'=>'11','lng'=>NULL,'lat'=>NULL,'is_show'=>'1','address_show'=>'1','type'=>'15','address'=>'','location_p'=>'1','location_c'=>'110000','location_a'=>'110101','roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-28 17:03:43','update_time'=>'2023-12-28 17:03:43']);
        $this->insert('{{%diandi_place_list}}',['id'=>'114','bloc_id'=>'91','store_id'=>'261','name'=>'23','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-28 17:05:01','update_time'=>'2023-12-28 17:05:01']);
        $this->insert('{{%diandi_place_list}}',['id'=>'115','bloc_id'=>'91','store_id'=>'262','name'=>'棋牌室测试','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'24','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 12:59:12','update_time'=>'2023-12-29 12:59:12']);
        $this->insert('{{%diandi_place_list}}',['id'=>'116','bloc_id'=>'91','store_id'=>'263','name'=>'公寓测试','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 13:09:15','update_time'=>'2023-12-29 13:09:15']);
        $this->insert('{{%diandi_place_list}}',['id'=>'117','bloc_id'=>'91','store_id'=>'264','name'=>'新酒店','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 15:49:13','update_time'=>'2023-12-29 15:49:13']);
        $this->insert('{{%diandi_place_list}}',['id'=>'118','bloc_id'=>'91','store_id'=>'265','name'=>'公寓6','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 15:55:24','update_time'=>'2023-12-29 15:55:24']);
        $this->insert('{{%diandi_place_list}}',['id'=>'119','bloc_id'=>'91','store_id'=>'266','name'=>'公寓6','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 15:57:17','update_time'=>'2023-12-29 15:57:17']);
        $this->insert('{{%diandi_place_list}}',['id'=>'120','bloc_id'=>'91','store_id'=>'267','name'=>'公寓测试','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 15:57:44','update_time'=>'2023-12-29 15:57:44']);
        $this->insert('{{%diandi_place_list}}',['id'=>'121','bloc_id'=>'91','store_id'=>'268','name'=>'32','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 15:59:39','update_time'=>'2023-12-29 15:59:39']);
        $this->insert('{{%diandi_place_list}}',['id'=>'122','bloc_id'=>'91','store_id'=>'269','name'=>'hhh','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 16:00:48','update_time'=>'2023-12-29 16:00:48']);
        $this->insert('{{%diandi_place_list}}',['id'=>'123','bloc_id'=>'91','store_id'=>'270','name'=>'公寓A','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 16:02:42','update_time'=>'2023-12-29 16:02:42']);
        $this->insert('{{%diandi_place_list}}',['id'=>'124','bloc_id'=>'91','store_id'=>'271','name'=>'公寓测试555','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 16:16:45','update_time'=>'2023-12-29 16:16:45']);
        $this->insert('{{%diandi_place_list}}',['id'=>'125','bloc_id'=>'91','store_id'=>'272','name'=>'2','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'18','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 16:36:24','update_time'=>'2023-12-29 16:36:24']);
        $this->insert('{{%diandi_place_list}}',['id'=>'126','bloc_id'=>'91','store_id'=>'273','name'=>'1号公寓','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 17:12:00','update_time'=>'2023-12-29 17:12:00']);
        $this->insert('{{%diandi_place_list}}',['id'=>'127','bloc_id'=>'91','store_id'=>'274','name'=>'5','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>NULL,'create_time'=>'2023-12-29 17:20:40','update_time'=>'2023-12-29 17:20:40']);
        $this->insert('{{%diandi_place_list}}',['id'=>'128','bloc_id'=>'91','store_id'=>'275','name'=>'12','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'24','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2023-12-30 00:56:36','update_time'=>'2023-12-30 00:56:36']);
        $this->insert('{{%diandi_place_list}}',['id'=>'129','bloc_id'=>'91','store_id'=>'276','name'=>'合租测试','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2023-12-30 01:15:08','update_time'=>'2023-12-30 01:15:08']);
        $this->insert('{{%diandi_place_list}}',['id'=>'130','bloc_id'=>'91','store_id'=>'277','name'=>'he1','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2023-12-30 01:40:13','update_time'=>'2023-12-30 01:40:13']);
        $this->insert('{{%diandi_place_list}}',['id'=>'131','bloc_id'=>'91','store_id'=>'278','name'=>'he2','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2023-12-30 01:43:09','update_time'=>'2023-12-30 01:43:09']);
        $this->insert('{{%diandi_place_list}}',['id'=>'132','bloc_id'=>'91','store_id'=>'279','name'=>'h566','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2023-12-30 01:43:19','update_time'=>'2023-12-30 01:43:19']);
        $this->insert('{{%diandi_place_list}}',['id'=>'133','bloc_id'=>'91','store_id'=>'280','name'=>'he-a','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'22','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'1','create_time'=>'2023-12-30 01:44:51','update_time'=>'2023-12-30 01:44:51']);
        $this->insert('{{%diandi_place_list}}',['id'=>'134','bloc_id'=>'91','store_id'=>'281','name'=>'测试1','lng'=>NULL,'lat'=>NULL,'is_show'=>'0','address_show'=>'0','type'=>'15','address'=>'','location_p'=>NULL,'location_c'=>NULL,'location_a'=>NULL,'roomcount'=>NULL,'status'=>'0','phone'=>NULL,'mail'=>NULL,'thumb'=>NULL,'description'=>NULL,'content'=>NULL,'traffic'=>NULL,'thumbs'=>NULL,'sales'=>NULL,'displayorder'=>'0','comment_num'=>'0','comment_start'=>NULL,'level'=>'0','device'=>NULL,'brandid'=>'0','language'=>'0','landlord_id'=>'1','apartment_type'=>'0','create_time'=>'2024-01-02 07:39:43','update_time'=>'2024-01-02 07:39:43']);
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }
    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%diandi_place_list}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}
